import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * Represents the response from a JSON API that includes a generated URL.
 *
 * @property generatedUrl The URL generated by the API.
 */
data class JSONResponse(
    /**
     * The URL generated by the API.
     * Serialized from the JSON field "generatedUrl".
     */
    @SerializedName("generatedUrl")
    val generatedUrl: String
) : Serializable
