package com.expert.qrgenerator.model

import androidx.room.ColumnInfo
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Data class representing a QR code entity in the Room database.
 *
 * @property login The login associated with the QR code.
 * @property qrId The unique identifier for the QR code.
 * @property userUrl The URL of the user associated with the QR code.
 * @property userType The type of user (e.g., admin, member).
 * @property generatedUrl The URL generated for the QR code.
 * @property id The unique primary key for the QR code entity, auto-generated by Room.
 */
//@Entity(tableName = "dynamic_qr_codes")
data class QREntity(
    @ColumnInfo(name = "login")
    val login: String,

    @ColumnInfo(name = "qrId")
    val qrId: String,

    @ColumnInfo(name = "userUrl")
    val userUrl: String,  // Consider making this immutable if it doesn't change

    @ColumnInfo(name = "userType")
    val userType: String, // Consider making this immutable if it doesn't change

    @ColumnInfo(name = "generatedUrl")
    val generatedUrl: String = "" // Consider making this immutable if it doesn't change
) : Serializable {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    var id: Int = 0 // Unique identifier for the QR code, auto-generated by Room
}
